### ISSUE TITLE
audios longer than 10 minutes

### ISSUE THREAD

**Issue by komangulo** [jianchang512/vocal-separate#1]
Hello friend!
In both the "4stems" model and the "2stems" model I only receive audios of 10 minutes maximum. The original video is 22 minutes.

How can I get an accompaniment or vocals audio of the same size as the original?
Thank you very much for your work.

你好，朋友！
无论是 "4stems "模式还是 "2stems "模式，我都只能收到最长 10 分钟的音频。原始视频为 22 分钟。

我怎样才能获得与原始视频同样大小的伴奏或人声音频？
非常感谢你们的工作。

![asdwd](https://github.com/jianchang512/vocal-separate/assets/43007108/10295bd6-142b-46f3-ac03-f3a77e95e41d)

**Comment by jianchang512** [comment]
fixed  0.0.3

**Comment by komangulo** [comment]
Hello!
The new version is working correctly and gives full audios with the same size/length.
Thank you very much :D


您好！
新版本已正常运行，并能提供大小/长度相同的完整音频。
非常感谢 :D

**Comment by muthuknm** [comment]
Hii
I'm unable to run the project. Can you please guide me?
