### ISSUE TITLE
戏曲分离优化

### ISSUE THREAD

**Issue by Liu8Can** [jianchang512/vocal-separate#6]
我测试了歌曲分离效果特别好，但是戏曲分离不恨理想，可能是传统乐器适配不太好。总体还是很好用的。

**Comment by jianchang512** [comment]
这是老外的模型，只是针对西方常见乐器训练的
你可以搜索下 uvr5 ，这个应该相对好点

**Comment by Liu8Can** [comment]
好的，谢谢
