### ISSUE TITLE
English Readme? and English vocal separation?

### ISSUE THREAD

**Issue by APISeeker** [jianchang512/vocal-separate#7]
Hello,
Does this technology work with all languages or it was trained only on chinese?
Also could you provide english version of the ReadMe please? I could not follow! Too much info 
Thanks

**Comment by jianchang512** [comment]
all languages

**Comment by APISeeker** [comment]
Is it better than decmus and "vocal-remover" please?

**Comment by jianchang512** [comment]
I'm not very familiar with that, but a better one would be UVR5

**Comment by APISeeker** [comment]
> I'm not very familiar with that, but a better one would be UVR5

Thank you you are a saint!
